### ISSUE TITLE
Having some trouble updating

### ISSUE THREAD

**Issue by ovizii** [mattermost/mattermost-docker#149]
I followed the instructions given here: https://github.com/mattermost/mattermost-docker 

> docker-compose down
> git pull
> docker-compose build
> docker-compose up -d

and got an error at the git pull part:

> git pull
> Your configuration specifies to merge with the ref 'refs/heads/team-and-enterprise'
> from the remote, but no such ref was fetched.

I am running:

> Mattermost Enterprise Edition
> 
> Modern communication from behind your firewall.
> 
> Version: 3.6.0  (3.6.2)
> Database: postgres

**Comment by pichouk** [comment]
It seems that your local Git repository is on `team-and-enterprise` branch but it doesn't exists anymore.
I think you should use `master` branch :
```
git checkout master
```

**Comment by ovizii** [comment]
I don't have much experience with git, I just remember following the instructions for how to install 3.6 back in the days. Does the command you gave above delete anything i.e. my dockerfile or the data?

**Comment by pichouk** [comment]
The command will set your local repository on the `master` branch, than you will be able to `git pull` to get the new code from Github. It should not delete your data (which is, I guess, in a `volumes/` folder) but it will modify the Dockerfile to the new version.

If you're really not confident, you could provide the result of the `git status` command to see how is your local repository currently.

**Comment by ovizii** [comment]
Well here it is: 

```
root@internal-docker:/mnt/mattermost-docker# git status
On branch team-and-enterprise
Your branch is up-to-date with 'origin/team-and-enterprise'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   docker-compose.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        volumes/

no changes added to commit (use "git add" and/or "git commit -a")
root@internal-docker:/mnt/mattermost-docker#

```

I can backup the files of course, do the command you suggested then adapt my docker file again? Am I the first one to upgrade from this team-and-enterprise version? (couldn't find anyone else with this issue)

**Comment by pichouk** [comment]
The `team-and-entreprise` seems to be an old branch, not existing anymore on this repository.

I suggest the following workaround :
```bash
cp docker-compose.yml /tmp/docker-compose.yml.save # Backup docker compose file
git stash # Stash changes
git checkout master # Checkout master branch
git pull origin master # Update master branch from repository
git stash pop # Unstash changes
```
At the last step, it is possible that you get an issue if you made a lot of modifications on your `docker-compose.yml`, that's why I suggest to backup it at the beginning. If you get any problem, you will just have to get your file back like this : `cp /tmp/ocker-xompose.yml.save docker-compose.yml`.

**Comment by ovizii** [comment]
Thanks for your help, I'll give that a try this weekend and will update this thread.

**Comment by pichouk** [comment]
@ovizii Did you succeed in updating your git repository ? :)

**Comment by ovizii** [comment]
sorry, I got side tracked so seeing your follow-up I just tried and followed your directives:

```
git stash
Saved working directory and index state WIP on team-and-enterprise: c59ac91 Export vars to fix the postgres container error
HEAD is now at c59ac91 Export vars to fix the postgres container error
```

```
 checkout master
Branch master set up to track remote branch master from origin.
Switched to a new branch 'master'
```

```
git pull origin master
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5 (delta 3), reused 5 (delta 3), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/mattermost/mattermost-docker
 * branch            master     -> FETCH_HEAD
   7590cef..c9a33c7  master     -> origin/master
Updating 7590cef..c9a33c7
Fast-forward
 app/docker-entry.sh | 11 ++++++++---
 1 file changed, 8 insertions(+), 3 deletions(-)
```

```
git stash pop
Auto-merging docker-compose.yml
CONFLICT (content): Merge conflict in docker-compose.yml
```
```

docker-compose build
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 2, column 8
```
getting this error with the new docker-compose.yml file so I have no placed my old docker-compose.yml file back and attempted docker-compose build + docker-compose up -d

but it fails:
```
...
mattermost/webapp/dist/5.2429f4590e5ccd71db19.js.map
  3 48.2M    3 1652k    0     0   5072      0  2:46:06  0:05:33  2:40:33     0
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
ERROR: Service 'app' failed to build: The command '/bin/sh -c mkdir -p /mattermost/data     && curl https://releases.mattermost.com/$MM_VERSION/mattermost-team-$MM_VERSION-linux-amd64.tar.gz | tar -xvz     && cp /mattermost/config/config.json /config.json.save     && rm -rf /mattermost/config/config.json' returned a non-zero code: 2
```
what do I do now?

**Comment by pichouk** [comment]
You have some merge-conflict on your `docker-compose.yml` file.
You have 2 options :
- solve the merge conflict : should open your `docker-compose.yml` to fix it
- use a new clean file and customize it with your volumes and passwords

If you have trouble, you could dump your file content here but **BE CAREFUL it may contain some sensitive data (username/password) that you should obfuscate first**.

**Comment by pichouk** [comment]
Hi @ovizii, did you manage to made it work ?

**Comment by ovizii** [comment]
thanks for checking in, its scheduled for this afternoon, it only became a priority now as some mobile clients demanded a newer server version :-) 
will update this thread in a few hours.

**Comment by ovizii** [comment]
oh, if you want to have a look, here is my "old" docker-compose file, there is absolutely nothing secret in there.

```
db:
  build: db
  restart: always
  volumes:
    - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  # uncomment the following to enable backup
  #environment:
  #  - AWS_ACCESS_KEY_ID=XXXX
  #  - AWS_SECRET_ACCESS_KEY=XXXX
  #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
  #  - AWS_REGION=us-east-1
app:
  build: app
  links:
    - db:db
  restart: always
  volumes:
    - ./volumes/app/mattermost/config:/mattermost/config:rw
    - ./volumes/app/mattermost/data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro
web:
  build: web
  ports:
    - "180:80"
    - "1443:443"
  links:
    - app:app
  restart: always
  volumes:
      # This directory must have cert files
    - ./volumes/web/cert:/cert:ro
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MATTERMOST_ENABLE_SSL=false
    - PLATFORM_PORT_80_TCP_PORT=80
```
