### ISSUE TITLE
mattermostdocker_app_1 exited with code 102

### ISSUE THREAD

**Issue by ionbasa** [mattermost/mattermost-docker#150]
Hi. 
I'm trying to run only the app and not web and db container. I already have a web server and database on the local machine.

So far, when trying to run docker compose up, I get the following error "mattermostdocker_app_1 exited with code 102"

My  docker-compose.yml file looks like this:
```
version: "2"

services:

  app:
    build:
      context: app
      # comment out for team edition
      dockerfile: Dockerfile-enterprise
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8065:8065"
      - "3307:3306"
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=********
      - MM_DBNAME=mattermost
      - DB_HOST=192.168.1.248
      - DB_PORT_NUMBER=3306
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
```
I also modified the docker-entry.sh file for app to look like the following: 
```
#!/bin/bash

generate_salt() {
  cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 48 | head -n 1
}

DB_HOST=${DB_HOST:-db}
DB_PORT_NUMBER=${DB_PORT_NUMBER:-5432}
MM_USERNAME=${MM_USERNAME:-mmuser}
MM_PASSWORD=${MM_PASSWORD:-mmuser_password}
MM_DBNAME=${MM_DBNAME:-mattermost}
MM_CONFIG=${MM_CONFIG:-/mattermost/config/config.json}

if [ "${1:0:1}" = '-' ]; then
    set -- platform "$@"
fi

if [ "$1" = 'platform' ]; then
    for ARG in $@;
    do
        case "$ARG" in
            -config=*)
                MM_CONFIG=${ARG#*=};;
        esac
    done


    if [ ! -f $MM_CONFIG ]
    then
      echo "No configuration file" $MM_CONFIG
      echo "Creating a new one"
      # Copy default configuration file
      cp /config.json.save $MM_CONFIG
      # Substitue some parameters with jq
      jq '.ServiceSettings.ListenAddress = ":8065"' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.LogSettings.EnableConsole = false' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.LogSettings.ConsoleLevel = "INFO"' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.FileSettings.Directory = "/mattermost/data/"' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.FileSettings.EnablePublicLink = true' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.FileSettings.PublicLinkSalt = "'$(generate_salt)'"' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.EmailSettings.SendEmailNotifications = false' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.EmailSettings.FeedbackEmail = ""' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.EmailSettings.SMTPServer = ""' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.EmailSettings.SMTPPort = ""' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.EmailSettings.InviteSalt = "'$(generate_salt)'"' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.EmailSettings.PasswordResetSalt = "'$(generate_salt)'"' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.RateLimitSettings.Enable = true' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.SqlSettings.DriverName = "mysql"' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
      jq '.SqlSettings.AtRestEncryptKey = "'$(generate_salt)'"' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG
    else
      echo "Using existing config file" $MM_CONFIG
    fi

    echo -ne "Configure database connection..."
    export MM_SQLSETTINGS_DATASOURCE="mysql://$MM_USERNAME:$MM_PASSWORD@$DB_HOST:$DB_PORT_NUMBER/$MM_DBNAME?sslmode=disable&connect_timeout=10"
    echo OK

    echo "Wait until database $DB_HOST:$DB_PORT_NUMBER is ready..."
    until nc -z $DB_HOST $DB_PORT_NUMBER
    do
        sleep 1
    done

    # Wait to avoid "panic: Failed to open sql connection pq: the database system is starting up"
    sleep 1

    echo "Starting platform"
fi

exec "$@"
```
Lastly, the Dockerfile-enterprise file was also adjusted to change the exposed port from 80 to 8065:
```
FROM ubuntu:14.04

# Some ENV variables
ENV PATH="/mattermost/bin:${PATH}"
ENV MM_VERSION=3.10.0

# Install some needed packages
RUN apt-get update \
    && apt-get -y install \
      curl \
      jq \
      netcat \
    && rm -rf /var/lib/apt/lists/*

# Prepare Mattermost
RUN mkdir -p /mattermost/data \
    && curl https://releases.mattermost.com/$MM_VERSION/mattermost-$MM_VERSION-linux-amd64.tar.gz | tar -xvz \
    && cp /mattermost/config/config.json /config.json.save \
    && rm -rf /mattermost/config/config.json

# Configure entrypoint
COPY docker-entry.sh /
# Set permission (TODO should be removed and replace by a chmod on the file in the repository ?)
RUN chmod +x /docker-entry.sh
ENTRYPOINT ["/docker-entry.sh"]

EXPOSE 8065
EXPOSE 3306

VOLUME /mattermost/data

WORKDIR /mattermost/bin
CMD ["platform"]
```
This configuration should work to my understanding, but I don't see why it is failing. The mattermost.log say the following:
```
[2017/07/03 11:34:54 PDT] [INFO] Enterprise Enabled: true
[2017/07/03 11:34:54 PDT] [INFO] Current working directory is /mattermost/bin
[2017/07/03 11:34:54 PDT] [INFO] Loaded config file from /mattermost/config/config.json
[2017/07/03 11:34:54 PDT] [INFO] Server is initializing...
[2017/07/03 11:34:54 PDT] [INFO] Pinging SQL master database
[2017/07/03 11:34:54 PDT] [CRIT] Failed to ping DB err:default addr for network '192.168.1.248:3306' unknown
[2017/07/03 11:35:48 PDT] [INFO] Loaded system translations for 'en' from '/mattermost/i18n/en.json'
[2017/07/03 11:35:48 PDT] [INFO] Current version is 3.10.0 (3.10.0/Wed Jun 14 21:03:15 UTC 2017/8b83e9d4279718c8f9797c6a9c081245231cbba0/7eab554702fb44fb7755e1a542cd7dd0d3acf261)
```

I don't understand how it is failing to ping the DB, its the proper address, username, password, and port.
