### ISSUE TITLE
Problem in creating an SSL certificate

### ISSUE THREAD

**Issue by DodgeCamaro** [mattermost/mattermost-docker#161]
I can not make a secure connection.
I tried to create on two instances. As an image [docker-preview](https://github.com/mattermost/mattermost-docker-preview) and [docker](https://github.com/mattermost/mattermost-docker).  

I created certificates in three ways:
1) Instructions for adding keys
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./volumes/web/cert/cert.pem -out ./volumes/web/cert/key-no-password.pem
2) Created in Letsencrypt, and then nginx was able to identify the keys, but could not use them, because `no found directory or file`
3) Created with the help of Openssl
sudo openssl x509 -req -days 3650 -in mattermost.csr -signkey mattermost.key -out mattermost.crt

Included, many times TLS,[ in two ways](https://docs.mattermost.com/install/config-tls-mattermost.html?highlight=tls), as indicated in the instruction, but none worked.

**Comment by pichouk** [comment]
Can you provide more information on your configuration please, like how did you run your containers (docker-compose file or command used) ?

What mean "can not make a secure connection" ? What is the result, do you have any log file ?

**Comment by DodgeCamaro** [comment]
I clone repository and run container with docker command with some amendments - `docker-compose up`.

This is my yml file
```
version: "2"

services:

  db:
    build: db
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  app:
    build:
      context: app
      # comment out for team edition
      dockerfile: Dockerfile-enterprise
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:Z
      - ./volumes/app/mattermost/data:/mattermost/data:Z
      - ./volumes/app/mattermost/logs:/mattermost/logs:Z
      - /etc/localtime:/etc/localtime:Z
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - MM_CONFIG=/mattermost/config/config.json
    links:
      - db:db

  web:
    build: web
    ports:
      - "80:80"
      - "443:443"
      - "8065:8065"
    restart: unless-stopped
    volumes:
      # This directory must have cert files
      - ./volumes/web/cert:/cert:Z
      - /etc/localtime:/etc/localtime:Z
    environment:
      - MATTERMOST_ENABLE_SSL= true
      - PLATFORM_PORT_80_TCP_PORT=80
    links:
      - app:app
```

Docker version 1.12.6, build 78d1802
docker-compose version 1.8.0, build unknown

I edit this:
![settings](https://user-images.githubusercontent.com/21026249/28880300-467e0e88-77ad-11e7-8348-282074ad734b.png)

This my latest log:
![502_error](https://user-images.githubusercontent.com/21026249/28880349-758341a8-77ad-11e7-8981-afd46273bd02.jpg)

Log when I created certificate, copy to `./volumes/web/cert/` and restart docker-compose.
![ssl](https://user-images.githubusercontent.com/21026249/28881194-0393ae2c-77b0-11e7-9899-c3ace9cfb282.jpg)
