### ISSUE TITLE
Docker versus docker-compose

### ISSUE THREAD

**Issue by linuxorbust** [mattermost/mattermost-docker#17]
How difficult would it be to build this without docker-compose?  Some detailed instructions would be great.

**Comment by xcompass** [comment]
You can pretty much convert docker-compose content line by line to a docker run command. e.g. for db service:
```
db:
  build: db
  volumes:
    - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  # uncomment the following to enable backup
  environment:
    - AWS_ACCESS_KEY_ID=XXXX
    - AWS_SECRET_ACCESS_KEY=XXXX
    - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    - AWS_REGION=us-east-1
```
to docker build and run
```
docker build -t mattermost-db db/
docker run \
  -v ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data \
  -v /etc/localtime:/etc/localtime:ro \
  -e AWS_ACCESS_KEY_ID=XXXX \
  -e AWS_SECRET_ACCESS_KEY=XXXX \
  -e WALE_S3_PREFIX=s3://BUCKET_NAME/PATH \
  -e AWS_REGION=us-east-1 \
mattermost-db
```
You can also push the images to dockerhub or use existing images from dockerhub ([db](https://hub.docker.com/r/compass/mattermost-db/) and [app](https://hub.docker.com/r/compass/mattermost-app/)) if you don't want to build the image yourself. Just replace the last line `mattermost-db` to `compass/mattermost-db`. (Hopefully these guys will do an automatic build on dockerhub so that I don't have to maintain mine.)
