### ISSUE TITLE
Run mattermost-prod-app 3.9.0 with MySQL,  fails

### ISSUE THREAD

**Issue by localsnet** [mattermost/mattermost-docker#173]
Hello folk.
I've been trying to run the mattermost with MySQL by docker-compose.yml .
After run docker-compose up on my output terminal I got:
> app_1  | Starting platform
> project_app_1 exited with code 102
> app_1  | Using config file /mattermost/config/config.json
> app_1  | Configure database connection...SKIP
> app_1  | Wait until database db:3306 is ready...
> app_1  | Starting platform
> app_1  | Using config file /mattermost/config/config.json
> app_1  | Configure database connection...SKIP
> app_1  | Wait until database db:3306 is ready...
In ./app/logs/mattermost.log:

> [2017/09/19 15:15:55 MSK] [INFO] Pinging SQL master database
> [2017/09/19 15:15:55 MSK] [CRIT] Failed to ping DB err:pq: unknown response for startup: 'J'
> [2017/09/19 15:15:59 MSK] [INFO] Loaded system translations for 'en' from '/mattermost/i18n/en.json'
> [2017/09/19 15:15:59 MSK] [INFO] Current version is 3.9.0 (3.9.0/Mon May 15 20:26:32 UTC 2017/ae3a62ef95e22ff67236e8addb1e4ca005307443/none)
> [2017/09/19 15:15:59 MSK] [INFO] Enterprise Enabled: false
> [2017/09/19 15:15:59 MSK] [INFO] Current working directory is /mattermost/bin
> [2017/09/19 15:15:59 MSK] [INFO] Loaded config file from /mattermost/config/config.json
> [2017/09/19 15:15:59 MSK] [INFO] Server is initializing...

The docker -compose.yml file:
```version: "2.1"
services:
  db:
    image: mysql:5.7
    container_name: ${DATABASE_HOST}
    restart: unless-stopped
    volumes:
      - /data/mattermost:/data/mattermost
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=bbbbbbbbb
      - MYSQL_ROOT_PASSWORD=cccccccccc
      - MYSQL_DATABASE=mattermost
    ports:
      - "3307:3306"
#    network_mode: bridge
    #dns: 

  app:
#    depends_on:
#     - db
    image: mattermost/mattermost-prod-app:3.9.0
    restart: unless-stopped
#    links:
#      - db:db
    volumes:
      - ./app/config:/mattermost/config:rw
      - ./app/data:/mattermost/data:rw
      - ./app/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    #  - ./data/hosts:/etc/hosts
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=bbbbbbbbb
      - MM_DBNAME=mattermost
      - DB_PORT_5432_TCP_PORT=3306
      - DB_HOST=${DATABASE_HOST}
    ports:
      - "8066:8065"
#    network_mode: bridge
#    sysctls: 
#      - net.ipv4.ip_forward=1
```
Also, I've just noticed about using mattermost with conjunction MySQL from official dockerhub repo:

> If you choose to use MySQL instead of PostgreSQL, you should set a different datasource :
> 
> MM_SQLSETTINGS_DATASOURCE : 

> "$MM_USERNAME:$MM_PASSWORD@tcp($DB_HOST:$DB_PORT_NUMBER)/$MM_DBNAME?

> charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"

Probably the problem  in that.
So, does I need to put  the above datasource in my compose file directly, or it should be place in Dockerfile (or entrypoint.sh)?
How I should resolve it?
Thank you in advance.

**Comment by pichouk** [comment]
You're right, you need to add the `MM_SQLSETTINGS_DATASOURCE`var on your docker compose file for the `app` container like this : 
```
  app:
#    depends_on:
#     - db
    image: mattermost/mattermost-prod-app:3.9.0
    restart: unless-stopped
#    links:
#      - db:db
    volumes:
      - ./app/config:/mattermost/config:rw
      - ./app/data:/mattermost/data:rw
      - ./app/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    #  - ./data/hosts:/etc/hosts
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=bbbbbbbbb
      - MM_DBNAME=mattermost
      - DB_PORT_5432_TCP_PORT=3306
      - DB_HOST=${DATABASE_HOST}
      - MM_SQLSETTINGS_DATASOURCE="$MM_USERNAME:$MM_PASSWORD@tcp($DB_HOST:$DB_PORT_NUMBER)/$MM_DBNAME?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"
    ports:
      - "8066:8065"
#    network_mode: bridge
#    sysctls: 
#      - net.ipv4.ip_forward=1
```

**Comment by localsnet** [comment]
@pichouk  MM_SQLSETTINGS_DATASOURCE didn't fit in the compose file, though.
I've just found this variable in ./app/docker-entry.sh , I've made the changes on MySQL set and modify new docker-compose file (from here). But still doesn't work.
Here is new compose file:
````
version: "2"

services:

  db:
   # build: db
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/mysql/data:/var/lib/mysql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
#      - POSTGRES_USER=mmuser
#      - POSTGRES_PASSWORD=mmuser_password
#      - POSTGRES_DB=mattermost
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=avdJHDhcdj&3
      - MYSQL_ROOT_PASSWORD=ds7873iud2d
      - MYSQL_DATABASE=mattermost

    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # comment out for team edition
      dockerfile: Dockerfile-enterprise
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
#      - MM_USERNAME=mmuser
#      - MM_PASSWORD=mmuser_password
#      - MM_DBNAME=mattermost
      - MM_USERNAME=mmuser
      - MM_PASSWORD=avdJHDhcdj&3
      - MM_DBNAME=mattermost
      - DB_PORT_NUMBER=3306
      - DB_HOST=db

      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
    links:
      - db:db

  web:
    build: web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      # This directory must have cert files
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - app:app
```
`

**Comment by pichouk** [comment]
What do you mean by "didn't fit in the compose file" ? It should work without modification of the Dockerfile or docker entrypoint.

**Comment by localsnet** [comment]
@pichouk 
I mean, that it doesn't work in compose file, amd I thought that it should be set in .app/docker-entry.sh  file. But both didn't help.
I've got the next errors  from docker-compose:

> local@w01:~/gitrepos/mattermost-docker$ docker-compose up
> WARNING: The MM_USERNAME variable is not set. Defaulting to a blank string.
> WARNING: The MM_PASSWORD variable is not set. Defaulting to a blank string.
> WARNING: The DB_HOST variable is not set. Defaulting to a blank string.
> WARNING: The DB_PORT_NUMBER variable is not set. Defaulting to a blank string.
> WARNING: The MM_DBNAME variable is not set. Defaulting to a blank string.
> Creating mattermostdocker_db_1 ... 
> Creating mattermostdocker_db_1 ... done
> Creating mattermostdocker_app_1 ... 
> Creating mattermostdocker_app_1 ... done
> Creating mattermostdocker_web_1 ... 
> Creating mattermostdocker_web_1 ... done
> Attaching to mattermostdocker_db_1, mattermostdocker_app_1, mattermostdocker_web_1
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:08.253293Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:08.254442Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> app_1  | No configuration file /mattermost/config/config.json
> db_1   | 2017-09-20T08:12:08.254458Z 0 [ERROR] Aborting
> web_1  | linking plain config
> app_1  | Creating a new one
> db_1   | 
> app_1  | Using existing database connection
> app_1  | Wait until database db:3306 is ready...
> mattermostdocker_db_1 exited with code 1
> app_1  | nc: getaddrinfo: Name or service not known
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:08.253293Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:08.254442Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:08.254458Z 0 [ERROR] Aborting
> db_1   | 
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:09.055706Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:09.056875Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:09.056893Z 0 [ERROR] Aborting
> db_1   | 
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:09.672469Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:09.673617Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:09.673632Z 0 [ERROR] Aborting
> db_1   | 
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:10.555050Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:10.556199Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:10.556213Z 0 [ERROR] Aborting
> db_1   | 
> app_1  | nc: getaddrinfo: Name or service not known
> mattermostdocker_db_1 exited with code 1
> app_1  | nc: getaddrinfo: Name or service not known
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:08.253293Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:08.254442Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:08.254458Z 0 [ERROR] Aborting
> db_1   | 
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:09.055706Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:09.056875Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:09.056893Z 0 [ERROR] Aborting
> db_1   | 
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:09.672469Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:09.673617Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:09.673632Z 0 [ERROR] Aborting
> db_1   | 
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:10.555050Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:10.556199Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:10.556213Z 0 [ERROR] Aborting
> db_1   | 
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:11.846311Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:11.847421Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:11.847437Z 0 [ERROR] Aborting
> db_1   | 
> db_1   | Initializing database
> db_1   | 2017-09-20T08:12:13.848295Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> db_1   | 2017-09-20T08:12:13.849431Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> db_1   | 2017-09-20T08:12:13.849447Z 0 [ERROR] Aborting
> db_1   | 
> mattermostdocker_db_1 exited with code 1

Also I've noticed: that my variables from compose file absent in config.json, and here some test (defaults) values. 
```
local@w01:~/gitrepos/mattermost-docker/volumes/app/mattermost/config$ grep DataSource config.json 
    "DataSource": "mmuser:mostest@tcp(dockerhost:3306)/mattermost_test?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s",
```
What is wrong ?
Thank you.

**Comment by pichouk** [comment]
Seems that there is an issue with your environment variables 
```
WARNING: The MM_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The MM_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_HOST variable is not set. Defaulting to a blank string.
WARNING: The DB_PORT_NUMBER variable is not set. Defaulting to a blank string.
WARNING: The MM_DBNAME variable is not set. Defaulting to a blank string.
```
Does `MM_SQLSETTINGS_DATASOURCE` is defined after thoses variables ? Because it seems not, so the string is wrong.

Another thing, your database seems to have an issue 
```
db_1 | Initializing database
db_1 | 2017-09-20T08:12:11.846311Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1 | 2017-09-20T08:12:11.847421Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
db_1 | 2017-09-20T08:12:11.847437Z 0 [ERROR] Aborting
```
If database is not working, your `app` container will not work. You should look at your MySQL container too.

About the variables that are not in the `config.json` file, maybe it is related with your PR https://github.com/mattermost/mattermost-docker/pull/174

**Comment by localsnet** [comment]
Definitely it was defined. As for DB, I've read that is not crucial problem, it can leave.
I've found something related to MySQL settings, https://github.com/mattermost/mattermost-server/pull/1946/files .

I think, that problem lies deeper than docker compose file. In docker-entry.sh and other and its companion source files. So to resolve it,  I need to understand how it works without containers.

**Comment by pichouk** [comment]
Ok, it seems that the database loop-start so it can be a problem. I let you check this.

`docker-entry.sh` is the entrypoint of the docker image. When you run the container, it call this script which configure the Mattermost `config.json` file, check the database is ready, and run Mattermost.

According to your logs, this script never reach the `docker-entry.sh` line 56 (and it should). Maybe the fix you proposed on your Pull Request solve this, did you try with this fix ?
If this line is not executed at startup, then there is a problem with your `MM_SQLSETTINGS_DATASOURCE` env var.

**Comment by localsnet** [comment]
@pichouk Well, you was right , problem with DB I resolve by temporary solution, I've just comment Volumes, I think some problems with permissions.
Because, the changes not happened to config.json with my variables, I've decide to use the default test values for environment consistency, so here changes
```
version: "2"

services:

  db:
   # build: db
    image: mysql:5.7
    restart: unless-stopped
    volumes:
#      - ./volumes/db/var/lib/mysql/data:/var/lib/mysql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
#      - POSTGRES_USER=mmuser
#      - POSTGRES_PASSWORD=mmuser_password
#      - POSTGRES_DB=mattermost
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mostest
      - MYSQL_ROOT_PASSWORD=mostest
      - MYSQL_DATABASE=mattermost_test

    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # comment out for team edition
      dockerfile: Dockerfile-enterprise
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
#      - MM_USERNAME=mmuser
#      - MM_PASSWORD=mmuser_password
#      - MM_DBNAME=mattermost
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mostest
      - MM_DBNAME=mattermost_test
      - DB_PORT_NUMBER=3306
      - DB_HOST=db
#      - MM_SQLSETTINGS_DATASOURCE="$MM_USERNAME:$MM_PASSWORD@tcp($DB_HOST:$DB_PORT_NUMBER)/$MM_DBNAME?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"
      # in case your config is not in default location
#      - MM_CONFIG=/mattermost/config/config.json
    links:
      - db:db

  web:
    build: web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      # This directory must have cert files
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - app:app
```
But success happened to me only, I've made some changes again to docker-entry.sh:
from 
`#      export MM_SQLSETTINGS_DATASOURCE="mysql://$MM_USERNAME:$MM_PASSWORD@$DB_HOST:$DB_PORT_NUMBER/$MM_DBNAME?sslmode=disable&connect_timeout=10"`
to    
  `export MM_SQLSETTINGS_DATASOURCE="$MM_USERNAME:$MM_PASSWORD@tcp($DB_HOST:$DB_PORT_NUMBER)/$MM_DBNAME?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"`

and replace postgres on the mysql:
`      jq '.SqlSettings.DriverName = "mysql"' $MM_CONFIG > $MM_CONFIG.tmp && mv $MM_CONFIG.tmp $MM_CONFIG`
So, why  my environment not applied to config.json file? But all variables present in containers when I checked it by env command.
