### ISSUE TITLE
PostgreSQL does not work with a persistent windows mount

### ISSUE THREAD

**Issue by tonylea** [mattermost/mattermost-docker#178]
`docker-compose` fails on Windows OS with the default docker-compose.yml. Error output is:

```
db_1   | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
db_1   | HINT:  The server must be started by the user that owns the data directory.
```

Further details on the issue can be found [here](https://github.com/jsreport/jsreport/issues/266).

I have successfully tested the workaround suggested [here](https://forums.docker.com/t/trying-to-get-postgres-to-work-on-persistent-windows-mount-two-issues/12456/5) to use docker to create the volume.

Suggest updating the README to add specific Windows OS note to:
- Create a docker volume: `docker volume create --name mattermost-postgresql-volume -d local`
- Update docker-compose.yml to below
 
```yml
version: "2"

services:

  db:
    build: db
    restart: unless-stopped
    volumes:
      - mattermost-postgresql-volume:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # comment out 2 following lines for team edition
      # args:
      #   - edition=team
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
    links:
      - db:db

  web:
    build: web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      # This directory must have cert files
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true
    links:
      - app:app

volumes:
  mattermost-postgresql-volume:
    external: true
```
