### ISSUE TITLE
Problems with Docker-compose

### ISSUE THREAD

**Issue by SerdarN92** [mattermost/mattermost-docker#179]
Hi Guys,

iam not so good with Docker-compose. I had an running instance of mattermost, but it was not from the right source.

docker run --name mattermost -d --link mattermost-mysql:mysql --expose 80 -e VIRTUAL_HOST=hq-platri.de -e LETSENCRYPT_EMAIL=info@platri.de -e LETSENCRYPT_HOST=hq-platri.de --env 'MATTERMOST_SECRET_KEY=U3SPhPTVV2jH3U3SPhPTVV2jH3U3SPhPTVV2jH3U3SPhPTVV2jH3' --env 'MATTERMOST_LINK_SALT=OZ7QckptSVi5kOZ7QckptSVi5kOZ7QckptSVi5kOZ7QckptSVi5k' --env 'MATTERMOST_RESET_SALT=9DLFSXZM2xwMG9DLFSXZM2xwMG9DLFSXZM2xwMG9DLFSXZM2xwMG' --env 'MATTERMOST_INVITE_SALT=col7hF4Jknrfucol7hF4Jknrfucol7hF4Jknrfucol7hF4Jknrfu' --volume /home/docker/mattermost/mattermost:/opt/mattermost/data jasl8r/mattermost:3.5.1

Normally i started it like this. Can someone help me to configure the docker-compuse like this?

**Comment by pichouk** [comment]
If you follow the steps from the README.md file, running Mattermost is easy.
I don't understand how it was working previously for you, especially what does your environments variables. I cannot help you to made works Let's encrypt as it was working before for example.

I see you use MySQL. We provide a docker-compose.yml file for PostgreSQL but you can use MySQL if you want with few modifications on the docker-compose file (as you can see in the README).

Maybe I can suggest a docker-compose file example if I know how you run your database and if you have a reverse proxy that terminate SSL for example.

**Comment by SerdarN92** [comment]
Could you suggest me a docker-compose file example with PostgreSQL and Nginx? Im running Nginx with automated certification over Let's encrypt.

**Comment by pichouk** [comment]
If your Nginx reverse proxy already works with Let's Encrypt, then you just need the App and Database container.

If you want to use PostgreSQL you can directly use the [`docker-compose.yml` file of this repository](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml) and remove the Web container. But if you run a new database, it will be a fresh new instance and your previous data wiil be lost.

If I assume that you want your data under `/home/docker/mattermost` I suggest running those commands (I assume the folder is empty):
```
cd /home/docker/mattermost
git clone https://github.com/mattermost/mattermost-docker.git ./
```

Then modify your `docker-compose.yml` file like this (don't forget to change database credentials and to uncomment the specified line if you use Team Edition) : 
```
version: "2"
services:
  db:
    build: db
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  app:
    build:
      context: app
      # comment out 2 following lines for team edition
      # args:
      #   - edition=team
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
    links:
      - db:db
```

Then run :

**Comment by SerdarN92** [comment]
Thank you for your answer! My Nginx reserve proxy already works with Let's encrypt. As example Wekan is working with no problems.

I want to use the team edition. What i have to change? when i comment out the 2 lines, it gives me an error.

And one more question. For lets encrypt i need those environment variables -e VIRTUAL_HOST=hq-platri.de -e LETSENCRYPT_EMAIL=info@platri.de -e LETSENCRYPT_HOST=hq-platri.de so my certificates will be renewed automatically. can i add them to the docker-compose file?

And what about expose 80 ? Do i need that?

**Comment by pichouk** [comment]
With the information you gave me, then you should use this file I guess :
```
version: "2"
services:
  db:
    build: db
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  app:
    build:
      context: app
      args:
        - edition=team
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - VIRTUAL_HOST=hq-platri.de
      - LETSENCRYPT_EMAIL=info@platri.de
      - LETSENCRYPT_HOST=hq-platri.de 
    links:
      - db:db
```

Port 80 is already exposed in the Dockerfile. Your reverse proxy just need to redirect traffic to the container (I guess that's what your environment variable does).
