### ISSUE TITLE
Mattermost with docker v1.7 / docker-compose v1.5

### ISSUE THREAD

**Issue by cbeldacap** [mattermost/mattermost-docker#191]
Hi,

Could it be some problems by using this mattermost `docker-compose` option under this environment specifications?
- OS: **RHEL 6.5**
- Docker: **v1.7**
- Docker-compose: **v1.5**

I've tried it by adapting the `docker-compose.yml` syntax (removing both `version` and `services` tags, but it does not work)

Any previous experience with it? If so, any specific changes on the compose file?

Thnx a lot in advance

**Comment by pichouk** [comment]
Our `docker-compose.yml` should be used for with docker-compose `1.6.0+` but I see no big problem if you change the file to made it works on an "old" version of Docker.
You can find an v1 `docker-compose.yml` file (not maintain anymore) [here](https://github.com/mattermost/mattermost-docker/blob/d3358cf2de5cfa524e763c057beed54452b4f76e/docker-compose-v1.yml). Maybe if you try to mix it with the new one (removing `versions` and `services`, but also add `links`) you should get something working.

Tell me if you have any troubles with that and I'll see if I can forge a `docker-compose.yml` file for v1.

**Comment by pichouk** [comment]
I think something like this should work :
```
db:
  build: db
  restart: unless-stopped
  volumes:
    - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  environment:
    - POSTGRES_USER=mmuser
    - POSTGRES_PASSWORD=mmuser_password
    - POSTGRES_DB=mattermost
  # uncomment the following to enable backup
  #  - AWS_ACCESS_KEY_ID=XXXX
  #  - AWS_SECRET_ACCESS_KEY=XXXX
  #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
  #  - AWS_REGION=us-east-1

app:
  build:
    context: app
    # comment out 2 following lines for team edition
    #args:
    #  - edition=team
  links:
    - db:db
  restart: unless-stopped
  volumes:
    - ./volumes/app/mattermost/config:/mattermost/config:rw
    - ./volumes/app/mattermost/data:/mattermost/data:rw
    - ./volumes/app/mattermost/logs:/mattermost/logs:rw
    - /etc/localtime:/etc/localtime:ro
  environment:
  # set same as db environment
    - MM_USERNAME=mmuser
    - MM_PASSWORD=mmuser_password
    - MM_DBNAME=mattermost
  # in case your config is not in default location
  #  - MM_CONFIG=/mattermost/config/config.json

web:
  build: web
  ports:
    - "80:80"
    - "443:443"
  links:
    - app:app
  restart: unless-stopped
  volumes:
      # This directory must have cert files
    - ./volumes/web/cert:/cert:ro
    - /etc/localtime:/etc/localtime:ro
  # Uncomment for SSL
  #environment:
  #  - MATTERMOST_ENABLE_SSL=true
```

**Comment by cbeldacap** [comment]
Hi @pichouk thanks for the hint!

But I'm afraid it always fail in the same place:
![image](https://user-images.githubusercontent.com/20857839/32316470-9edf1f36-bfb0-11e7-8086-908ccba6af61.png)

Versions:
![image](https://user-images.githubusercontent.com/20857839/32316501-bf3a35a4-bfb0-11e7-8840-005273065623.png)

**Comment by pichouk** [comment]
Hmm I forgot that docker-compose version 1 seems to not support `build` arguments... (it is mentioned [here](https://docs.docker.com/compose/compose-file/compose-file-v1/#build)).

I think you need to remove all `build` key from the `docker-compose.yml` file and use `image` keys. Then, you need to build images by yourself or use those on Docker Hub. Something like this can work :
```
db:
  image: mattermost/mattermost-prod-db
  restart: unless-stopped
  volumes:
    - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  environment:
    - POSTGRES_USER=mmuser
    - POSTGRES_PASSWORD=mmuser_password
    - POSTGRES_DB=mattermost
  # uncomment the following to enable backup
  #  - AWS_ACCESS_KEY_ID=XXXX
  #  - AWS_SECRET_ACCESS_KEY=XXXX
  #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
  #  - AWS_REGION=us-east-1

app:
  image: mattermost/mattermost-prod-app
  links:
    - db:db
  restart: unless-stopped
  volumes:
    - ./volumes/app/mattermost/config:/mattermost/config:rw
    - ./volumes/app/mattermost/data:/mattermost/data:rw
    - ./volumes/app/mattermost/logs:/mattermost/logs:rw
    - /etc/localtime:/etc/localtime:ro
  environment:
  # set same as db environment
    - MM_USERNAME=mmuser
    - MM_PASSWORD=mmuser_password
    - MM_DBNAME=mattermost
  # in case your config is not in default location
  #  - MM_CONFIG=/mattermost/config/config.json

web:
  image: mattermost/mattermost-prod-web
  ports:
    - "80:80"
    - "443:443"
  links:
    - app:app
  restart: unless-stopped
  volumes:
      # This directory must have cert files
    - ./volumes/web/cert:/cert:ro
    - /etc/localtime:/etc/localtime:ro
  # Uncomment for SSL
  #environment:
  #  - MATTERMOST_ENABLE_SSL=true
```

**Comment by pichouk** [comment]
Is that solved for you @cbeldacap ? :)

**Comment by cbeldacap** [comment]
@pichouk Sorry for the lack of feedback. Actually I've addapted the `docker-compose.yml` to that syntax and it kept giving me some errors. It seems that, in the end, I didn't have `docker-compose` in my `sudo` PATH (such a basic mistake ¬¬)

Once I've added it, I was able to run Mattermost with that last syntax you posted in here :)

Just to resume:
- **OS**: RHEL 6.5
- **docker**: `Docker version 1.7.1, build 786b29d/1.7.1`
- **docker-compose**: `docker-compose version 1.5.2, build 7240ff3`

docker-compose syntax for those requirements:
----------------------------------------------------
```
db:
  image: mattermost/mattermost-prod-db
  restart: unless-stopped
  volumes:
    - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  environment:
    - POSTGRES_USER=mmuser
    - POSTGRES_PASSWORD=mmuser_password
    - POSTGRES_DB=mattermost

app:
  image: mattermost/mattermost-prod-app
  links:
    - db:db
  restart: unless-stopped
  volumes:
    - ./volumes/app/mattermost/config:/mattermost/config:rw
    - ./volumes/app/mattermost/data:/mattermost/data:rw
    - ./volumes/app/mattermost/logs:/mattermost/logs:rw
    - /etc/localtime:/etc/localtime:ro
  environment:
    - MM_USERNAME=mmuser
    - MM_PASSWORD=mmuser_password
    - MM_DBNAME=mattermost

web:
  image: mattermost/mattermost-prod-web
  ports:
    - "8088:80"
    - "8089:443"
  links:
    - app:app
  restart: unless-stopped
  volumes:
    - ./volumes/web/cert:/cert:ro
    - /etc/localtime:/etc/localtime:ro
```

Thanks a lot for the info and support @pichouk
