### ISSUE TITLE
Mattermost app container block in Starting platform

### ISSUE THREAD

**Issue by smileisak** [mattermost/mattermost-docker#211]
Trying to deploy mattermost app in kuberenetes cluster.

Database: `Postgresql` (External)

Deployment:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mattermost-app
  labels:
    app: mattermost
    tier: app
spec:
  replicas: 1
  template:
    metadata:
      name: mattermost-app
      labels:
        app: mattermost
        tier: app
    spec:
      containers:
      - name: mattermost-app
        image: "mattermost/mattermost-prod-app:4.4.2"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: db-port
        - name: MM_USERNAME
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: mm-username
        - name: MM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: mm-password
        - name: MM_DBNAME
          valueFrom:
            secretKeyRef:
              name: mattermost.env
              key: mm-dbname
        volumeMounts:
        # optional persistant storage
        - name: appdata
          mountPath: /mattermost/data
        - name: etclocaltime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      # optional persistant storage
      - name: appdata
        hostPath:
          path: /opt/muttermost
      - name: etclocaltime
        hostPath:
          path: /etc/localtime
```
When creating this deployment, it creates one mattermost app pod that blocks in `starting platform`

Pod:

    kubectl get pods
    NAME                              READY     STATUS    RESTARTS   AGE
    mattermost-app-68b5778f5d-tzztn   1/1       Running   0          <invalid>

Logs:
    
    kubectl logs -f mattermost-app-68b5778f5d-tzztn
   
    No configuration file /mattermost/config/config.json
    Creating a new one
    Configure database connection...OK
    Wait until database 10.244.214.98
    :5432 is ready...
    Starting platform
