### ISSUE TITLE
Docker-compose up error when using mysql.

### ISSUE THREAD

**Issue by hzwzw** [mattermost/mattermost-docker#292]
Hey, 
I have to use mysql instead of pg because of some reasons.
And the process really tough since lack of complete docker-compose file for MYSQL, only some code snippet. It's really hard for newbie.

For example, when there's some error about 'cannot write xxx'. It takes me a lot of time to realize I should comment the `read_only:true` in below. I wanna know what the 'read_only:true' mean in the context? If there any unhappy things happen if I comment this line?

from docker-compose.yml
```
services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
```

And if somebody would like offer a complete config file for MySQL, many people will really appreciate it.

Thank you!
