### ISSUE TITLE
team edition

### ISSUE THREAD

**Issue by neuromancer-es** [mattermost/mattermost-docker#343]
When selecting the team version following documentation i get the following error:
_Bear in mind first time docker-compose and I don't understand yaml_

```
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 24, column 7
expected <block end>, but found '<block sequence start>'
  in "./docker-compose.yml", line 27, column 10
```

Here a slightly more detailed version with a yaml
https://1n.pm/V1L6E

What am I missing? is the docker-compose file correct for this setting?

Thank you

**Comment by pichouk** [comment]
Hi, can you paste the content of your `docker-compose.yml` file please ? It seems that the YAML is broken, maybe you made a syntax error when trying to modify the file.

**Comment by neuromancer-es** [comment]
Thank you pichouk. File was linked in the issue.

I have now fixed it by properly indenting the file:

__BEFORE (NOT WORKING)__
```
    build:
      context: app
        args:
         - edition=team
      #   - PUID=1000
      #   - PGID=1000
```
__AFTER (WORKING)__
```
  app:
    build:
        context: app
        args:
           - edition=team
      #   - PUID=1000
      #   - PGID=1000
```
