### ISSUE TITLE
Docker Swarm mode on multiple nodes

### ISSUE THREAD

**Issue by claudiacorreia60** [mattermost/mattermost-docker#349]
In the _Installation using Docker Swarm Mode_ section it says that those instructions are only useful for docker swarm mode in one node. I need to deploy Mattermost in a multi-node swarm. Thus, could you please help me figuring out what changes would I have to make to the _Dockerfiles_ and the _contrib/swarm/docker-stack.yml_ file so this would work?
When using the files created for one node, the app service fails with the error `task: non-zero exit (2): dockerxec: unhealthy container` and the nginx service fails with `host not found in upstream "app" in /etc/nginx/conf.d/mattermost.conf:21`.

**Comment by Pollard060** [comment]
@pichouk

**Comment by pichouk** [comment]
Hi :)
I'm sorry I don't have a swarm cluster to made some test. I never used this Swarm configuration (which is in the `contrib` part of the repository), maybe you can try to ping some people that contributed on [this file](https://github.com/mattermost/mattermost-docker/blob/master/contrib/swarm/docker-stack.yml) for help on this issue. (cc @Schrooms @kaakaa @pdemagny @ulm0 )

**Comment by Pollard060** [comment]
I created the swarm on Google Cloud Platform, I don't know if the errors I'm getting can be related with that. Maybe I have to also configure the firewall in the VM instances for this to work. What I'm doing is:
1. Creating VM instances on GCP using Ansible;
2. Creating the swarm with `docker swarm init --advertise-addr <ip_address>` and joining the other nodes;
3. Deploying the stack with `docker stack deploy -c docker-stack.yml mattermost`.

Everything works fine on one node, but I would like to deploy Mattermost in a multi-node swarm.
Thank you!

**Comment by Madko** [comment]
@Pollard060 I've got the very same error with a docker swarm in 3 VM. So it's not related to GCP. 
I don't understand why this web container can't resolve the "app" hostname.

There is also something wrong with this stack since it uses a volume for SSL certs files, but the web container (again) is only exposing port 80.

If I remove this app container, and export port 8000 from the app container, it works. Next I will try the traefik stack.

I've got other running stacks (like portainer to administrate this cluster) with no problem.

**Comment by Pollard060** [comment]
@Madko when you removed the web container and exported port 8000 from the app container, did you have the database container and the app running on different VMs? When I tried to do that I still got the error `task: non-zero exit (2): dockerxec: unhealthy container` on the app container.

**Comment by Madko** [comment]
Yes the app container and the db are on different nodes:

```
[root@controller-0 ~]# docker stack ps mattermost
ID                  NAME                IMAGE                                   NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
lmln6hiboj5k        mattermost_app.1    mattermost/mattermost-prod-app:latest   dockernode-0        Running             Running 6 minutes ago                       
tp9i7k3esft3        mattermost_db.1     mattermost/mattermost-prod-db:latest    dockernode-1        Running             Running 7 minutes ago     
```

[capture](https://www.linuxed.net/wp-content/uploads/captures/portainer/FireShot-Capture-2-Portainer-http___192.168.2.100_9000__swarm_visualizer.png)
[the stack I'm actually using](https://paste.fedoraproject.org/paste/VLHvVPoJYi7SFOqNFJpx9w)

**Comment by Schrooms** [comment]
@Pollard060 does changing the web service into this help?
```yaml
    # use official mattermost prod-web image
    image: mattermost/mattermost-prod-web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mm-out
    volumes:
      # This directory must have cert files
      - /var/lib/mattermost/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # use app service's hostname
      - APP_HOST=app
      # talk to the port within the overlay network
      # without (over)exposing ports
      - APP_PORT_NUMBER=8000 # <<<=== this is changed
    deploy:
      restart_policy:
       condition: on-failure
```
I got it working eventually but it is Incorporated in our own nginx config.
The most important this was that de app service exposed 8000 but the web service used port 80 to connect to the app service

If this works can you let me know, the I will change the compose file
