### ISSUE TITLE
Invalid site url

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [mattermost/mattermost-docker#414]
I followed the steps in the readme but I m getting an 

```sh
Error: failed to load: invalid config: Config.IsValid: model.config.is_valid.site_url.app_error
```
my docker.compose.yml
```
version: "2"

networks:
  web:
    external: true

services:
  app:
    build:
      context: app
      args:
        - edition=team
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_SQLSETTINGS_DATASOURCE=postgres://$user:$psswd0@$db-host:$port/$db?sslmode=require
      - MM_SERVICESETTINGS_SITEURL="http://mm.my-domain.com"
    container_name: MatterMost
    ports:
      - "8099:8000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:mm.my-domain.com"
      - "traefik.port=8099"
      - "traefik.protocol=http"
```

My site_url wasn't added to my config.json so I added it manually as "http://mm.my-domain.com" in SiteURL under ServiceSettings.

I also needed to change my SqlSettings manually

What am I doing wrong here?
