### ISSUE TITLE
Where are the mattermost credentials set ?

### ISSUE THREAD

**Issue by Docteur-RS** [mattermost/mattermost-docker#417]
Hey !

# Where are the mattermost credentials set ???

How can I not find this information ? Seriously, I feel like an idiot asking this but I'm stuck at the login page...

This is my docker-compose configuration :

```docker
version: "2"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
  app:
    build:
      context: app
      #args:
       #- edition=team
       #- PUID=1000
       #- PGID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    ports:
      - "8080:80"
      - "8443:443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true
```

I tried *mmuser* and *mmuser_password* as last resort but it didn't work.

**Comment by cpanato** [comment]
hello @Docteur-RS
which type of credentials are you talking about? to login in the mattermost ? if is this what are you looking for when the server is running you will need to create the user to access.

**Comment by Docteur-RS** [comment]
@cpanato Thx for your answer.  

I'm stuck on the login page where a login and password are asked ! On some software there's a default password or something to set in the docker compose. But for mattermost I can't find anything on the internet about that subject.

Based on your answer I tried the following command line:  
 `docker exec -it e110369c9eb5 mattermost user create --email hello@world.com --username randomguy--password randompasswd`

But I got:
```json
{"level":"error","ts":1569502805.026642,"caller":"sqlstore/supplier.go:236","msg":"Failed to ping DB retrying in 10 seconds err=dial tcp [::1]:5432: connect: connection refused"}
```

Is this the right way to create the first user and I'm experiencing a configuration issue **or** this is not the right way and I should not care about the error (fo now at least XD)  

Thx

**Comment by cpanato** [comment]
for this looks like the mattermost cannot the DB.

**Comment by Docteur-RS** [comment]
Yeah... Nothing appears within `docker logs` however...

**Comment by Docteur-RS** [comment]
Ok, so you don't have to create the users yourself...  
My DB was unhealthy and this was preventing the application to redirect me toward the signup page (Instead took me to the login page!).

The following docker-compose is working for me. Hope it can help someone else:
```
version: "2"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    #volumes:
      #- ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      #- /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      # args:
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    #volumes:
      #- ./volumes/app/mattermost/config:/mattermost/config:rw
      #- ./volumes/app/mattermost/data:/mattermost/data:rw
      #- ./volumes/app/mattermost/logs:/mattermost/logs:rw
      #- ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      #- ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      #- /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    ports:
      - "8080:80"
      - "8443:443"
    read_only: true
    restart: unless-stopped
    #volumes:
      # This directory must have cert files if you want to enable SSL
      #- ./volumes/web/cert:/cert:ro
      #- /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true
```
