### ISSUE TITLE
lookup db on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by ihack2712** [mattermost/mattermost-docker#419]
# Mattermost Version

5.16.0

# Issue

I get an error saying that lookup on db fails on host `127.0.0.11:53`. This is not where my db is located. I run mattermost and postgres in a docker compose file:

```yaml
  #
  # Mattermost: PostgreSQL Databse
  #
  mattermost-postgresql:
    build:
      context: "./build/mattermost-postgresql"
    restart: "unless-stopped"
    volumes:
      - "./services/mattermost-postgresql/data:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "POSTGRES_USER=mattermost"
      - "POSTGRES_PASSWORD=***"
      - "POSTGRES_DB=mattermost"
    networks:
      dev:
        ipv4_address: "172.25.0.103"
  
  #
  # Mattermost
  #
  mattermost:
    build:
      context: "./build/mattermost"
    restart: "unless-stopped"
    depends_on:
      - "mattermost-postgresql"
    volumes:
      - "./services/mattermost/config:/mattermost/config"
      - "./services/mattermost/data:/mattermost/data"
      - "./services/mattermost/logs:/mattermost/logs"
      - "./services/mattermost/plugins:/mattermost/plugins"
      - "./services/mattermost/client-plugins:/mattermost/client-plugins"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "MM_USERNAME=mattermost"
      - "MM_PASSWORD=***"
      - "MM_DBNAME=mattermost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.rule=Host(`chat.******.***`)"
      - "traefik.http.routers.mattermost.entrypoints=https"
      - "traefik.http.routers.mattermost.tls=true"
      - "traefik.http.routers.mattermost.tls.certresolver=dev"
    networks:
      dev:
        ipv4_address: "172.25.0.104"
```

The error it gives me is;
```log
2019-10-22T15:22:07.354+0200	info	utils/i18n.go:83	Loaded system translations	{"for locale": "en", "from locale": "/mattermost/i18n/en.json"}
2019-10-22T15:22:07.354+0200	info	app/server_app_adapters.go:59	Server is initializing...
2019-10-22T15:22:07.358+0200	info	sqlstore/supplier.go:222	Pinging SQL	{"database": "master"}
2019-10-22T15:22:07.361+0200	error	sqlstore/supplier.go:234	Failed to ping DB	{"error": "dial tcp: lookup db on 127.0.0.11:53: no such host", "retrying in seconds": 10}
```

I tried changing `SqlSettings.DataSource` (in the config.json file that mattermost generated) to
```
postgres://mattermost:***@172.25.0.103:8000/mattermost_test?sslmode=disable&connect_timeout=10
```

The only things I changed was authentication, host and port, so it would match the credentials and host and port I configured in the docker-compose file and the entrypoint.sh file for postgres.

The postgres database starts up successfully on port 8000 on host 172.25.0.103. But Mattermost doesn't seem to use my configurations.

Help is very appreciated.

Thanks,
Richard :)

**Comment by JonasGovaerts** [comment]
Having the same issue here

**Comment by iwittkau** [comment]
Same here.

**Comment by iwittkau** [comment]
@ihack2712 

> I get an error saying that lookup on db fails on host 127.0.0.11:53. This is not where my db is located.

Your are misunderstanding this error message: the app container tries to look up the db-host on its own DNS, which is at `127.0.0.11:53`. AFAIK mattermost tries to connect to a database via the hostname `db`. Your DB is named `mattermost-postgresql` that is why the lookup fails in your case.

In my case docker does not assign an IP address to the database container, which is most likely a bug in docker not mattermost.

**Comment by iwittkau** [comment]
Update: my db container does not have an IP address because it is stuck in a restart loop. So maybe my real problem is #428?

**Comment by ihack2712** [comment]
I just read on a cheatsheet that you can set your own hostnames inside of a docker-compose service. Meaning that I can keep my `mattermost-postgresql` name and still have mattermost being able to locate the db.

```yaml
  #
  # Mattermost: PostgreSQL Databse
  #
  mattermost-postgresql:
    build:
      context: "./build/mattermost-postgresql"
    restart: "unless-stopped"
    volumes:
      - "./services/mattermost-postgresql/data:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "POSTGRES_USER=mattermost"
      - "POSTGRES_PASSWORD=***"
      - "POSTGRES_DB=mattermost"
    networks:
      dev:
        ipv4_address: "172.25.0.103"
  
  #
  # Mattermost
  #
  mattermost:
    build:
      context: "./build/mattermost"
    restart: "unless-stopped"
    depends_on:
      - "mattermost-postgresql"
    volumes:
      - "./services/mattermost/config:/mattermost/config"
      - "./services/mattermost/data:/mattermost/data"
      - "./services/mattermost/logs:/mattermost/logs"
      - "./services/mattermost/plugins:/mattermost/plugins"
      - "./services/mattermost/client-plugins:/mattermost/client-plugins"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "MM_USERNAME=mattermost"
      - "MM_PASSWORD=***"
      - "MM_DBNAME=mattermost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.rule=Host(`chat.******.***`)"
      - "traefik.http.routers.mattermost.entrypoints=https"
      - "traefik.http.routers.mattermost.tls=true"
      - "traefik.http.routers.mattermost.tls.certresolver=dev"
    networks:
      dev:
        ipv4_address: "172.25.0.104"
    extra_hosts: # <-- this is how the db can be located.
      - "db:172.25.0.103"
```
