### ISSUE TITLE
[Feature request] Adding the host's trusted certificates to app container automatically

### ISSUE THREAD

**Issue by santiago-espinosa** [mattermost/mattermost-docker#429]
# The problem
The Mattermost app container does not automatically trust the same certificates as the host machine, even if the certificates are install in the host's CA store

I discovered this when trying to integrate webhooks with a self-hosted instance of GitLab that uses a self-signed certificate: [There's an easy way to add the certificates to the container](https://stackoverflow.com/questions/26028971/docker-container-ssl-certificates), but considering they're using the CLI, any reboot of the container will require running the command again. If the CA certificate addition is done in the docker-compose.yml file or the entrypoint.sh, it can be configured to automatically be done without any user intervention.

# Proposed solution

### Part 1
Add another volume that contains the host server's CAs and mounts them into the Mattermost app container's CA store.

Something like this for CentOS (see last line) where the folder for custom certs (`/etc/pki/ca-trust/sources`) is mounted in Ubuntu's folder for custom CA certs (`/usr/local/share/ca-certificate`):

```
.
.
  app:
    user: root
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      # args:
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    volumes:
      - /datadrive/volumes/app/mattermost/config:/mattermost/config:rw
      - /datadrive/volumes/app/mattermost/data:/mattermost/data:rw
      - /datadrive/volumes/app/mattermost/logs:/mattermost/logs:rw
      - /datadrive/volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - /datadrive/volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/pki/ca-trust/sources:/usr/local/share/ca-certificates:ro
.
.
```

### Part 2

Add `update-ca-certificates` to entrypoint.sh so that it is run when the container is put up:
```
.
.
  else
    echo "Using existing database connection"
  fi
  update-ca-certificates
  # Wait another second for the database to be properly started.
  # Necessary to avoid "panic: Failed to open sql connection pq: the database system is starting up"
  sleep 1

  echo "Starting mattermost"
fi

exec "$@"
.
.
```

Let me know if you would like me to submit a merge/pull request, I'd be more than happy to contribute.
