### ISSUE TITLE
app container cant connect to db container

### ISSUE THREAD

**Issue by heywiki** [mattermost/mattermost-docker#477]
Problem is described here: https://forum.mattermost.org/t/app-cant-connect-to-the-database/9617, since already three users reported this it might be worth investigating. Error message is

```
{“level”:“error”,“ts”:1587831029.9178288,“caller”:“sqlstore/supplier.go:218”,“msg”:“Failed to open SQL connection to err.”,“error”:“default addr for network ‘db:5432’ unknown”}
```

**Comment by jehos** [comment]
same++

**Comment by umlaeute** [comment]
the problem seems to be one of the [go mysql driver](https://github.com/go-sql-driver/mysql/issues/427), and the solution is pretty simple: put s`tcp()` around the host:port part. as in:

>  MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:secret@tcp(db:5432)/mattermost?sslmode=disable&connect_timeout=10

took me only an hour :-(

**Comment by parsifallo** [comment]
Won’t work for me with Postgres:12 database. Error message is „invalid port“

**Comment by umlaeute** [comment]
i'm using the `mattermost/mattermost-prod-db` image (which i think comes with PostgreSQL-9.4).

also, i think i got this when i only put the hostname in the `tcp()` clause (and not the `hostname:port` tuple).

in any case, it's still not working as is, as now the app cannot "ping" the database:

~~~
app_1  | {"level":"info","ts":1594295367.7590437,"caller":"sqlstore/supplier.go:227","msg":"Pinging SQL","database":"master"}
db_1   | LOG:  incomplete startup packet
app_1  | {"level":"error","ts":1594295377.759403,"caller":"sqlstore/supplier.go:239","msg":"Failed to ping DB","error":"context deadline exceeded","retrying in seconds":10}
~~~

**Comment by Salatfreak** [comment]
If you are using a docker image different than the one supplied in this repository you are likely missing the MM_SQLSETTINGS_DRIVERNAME=postgres environment variable. Here is a minimal working docker-compose.yml for the official mattermost-team-edition and postgres images:
```yaml

version: "3"
volumes:
  db:
  config:
  data:
  logs:
  plugins:
  client-plugins:
services:
  db:
    image: postgres:12-alpine
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=mattermost
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=<PASSWORD>
    restart: always
  app:
    image: mattermost/mattermost-team-edition:release-5.25
    ports:
      - 127.0.0.1:8080:8065
    volumes:
      - config:/mattermost/config
      - data:/mattermost/data
      - logs:/mattermost/logs
      - plugins:/mattermost/plugins
      - client-plugins:/mattermost/client/plugins
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_LOGSETTINGS_CONSOLELEVEL=ERROR
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:<PASSWORD>@db:5432/mattermost?sslmode=disable&connect_timeout=10
    restart: always
```
