### ISSUE TITLE
Not compatible with docker networks

### ISSUE THREAD

**Issue by SolidNerd** [mattermost/mattermost-docker#48]
Hey,
I tested your docker-compose file and it's not working with `docker networks`
I get repetitively the following error : 
 `mattermost_1  | nc: getaddrinfo: Name or service not known`. 
Here is my `docker-compose.yml` if you need more information let me know.
```yaml
version: '2'
services:
  db:
    build: db
    volumes:
    - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime:ro
  mattermost:
    build: app
    links:
      - db:db
    networks:
      - nginx
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - /etc/localtime:/etc/localtime:ro
networks:
  nginx:
    external: true
```
