### ISSUE TITLE
Error in URL sent to users when using custom port for Mattermost ListenURL. 

### ISSUE THREAD

**Issue by Niceplace** [mattermost/mattermost-docker#87]
Because mutliple applications are hosted on the server that runs the mattermost-docker project, I forwarded port 11443 of my host to the port 443 of the _**web**_ container.

I really had a hard time getting https configuration working and I kept getting "502 Bad gateway" errors from nginx. I eventually got it but there is a problem.

I want the users to be able to sign-up automatically and I want them to verify their email adresses. SMTP works like a charm but the problem is the URL that gets sent to the user via email does not include my custom port. 

TL;DR

Problem : URL for mattermost being sent in email to users does not contain custom port after the hostname. (i.e. https://mattermost.example.com:443/blablabala instead of https://mattermost.example.com:11443/blablabla).

Here are relevant config files

docker-compose.yml

```
version: "2"

services:

  db:
    build:
      context: ./db
      args:
        proxy: "[redacted]"
        sproxy: "[redacted]"
        noproxy: "[redacted]"
    restart: always
    volumes:
      - /app/docker-volumes/mattermost/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost

  app:
    build:
      context: ./app
        proxy: "[redacted]"
        sproxy: "[redacted]"
        noproxy: "[redacted]"
    links:
      - db:db
    restart: always
    volumes:
      - /app/docker-volumes/mattermost/mattermost/config:/mattermost/config:rw
      - /app/docker-volumes/mattermost/mattermost/data:/mattermost/data:rw
      - /etc/localtime:/etc/localtime:ro

  web:
    build:
      context: ./web
      args:
        proxy: "[redacted]"
        sproxy: "[redacted]"
        noproxy: "[redacted]"
    ports:
      - "11443:443"
    links:
      - app:app
    restart: always
    volumes:
        # This directory must have cert files
      - /app/docker-volumes/mattermost/mattermost/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MATTERMOST_ENABLE_SSL=true
      - PLATFORM_PORT_80_TCP_PORT=80
```

"ServiceSettings" of config.json

```
"ServiceSettings": {
        "SiteURL": "https://[redacted]:11443",
        "ListenAddress": ":80",
        "ConnectionSecurity": "TLS",
        "TLSCertFile": "/cert/oss-mattermost.cer",
        "TLSKeyFile": "/cert/oss-mattermost.key",
        "MaximumLoginAttempts": 10,
        "SegmentDeveloperKey": "",
        "GoogleDeveloperKey": "",
        "EnableOAuthServiceProvider": false,
        "EnableIncomingWebhooks": false,
        "EnableOutgoingWebhooks": false,
        "EnablePostUsernameOverride": false,
        "EnablePostIconOverride": false,
        "EnableTesting": false,
        "EnableSecurityFixAlert": true
    }
```

Dockerfile for **_app_**

```
FROM ubuntu:14.04

ARG proxy
ARG sproxy
ARG noproxy

ENV http_proxy="$proxy"
ENV https_proxy="$sproxy"
ENV no_proxy="$noproxy"

RUN apt-get update && apt-get -y install curl netcat
RUN mkdir -p /mattermost/data

RUN curl https://releases.mattermost.com/3.6.0/mattermost-3.6.0-linux-amd64.tar.gz | tar -xvz

RUN rm /mattermost/config/config.json
COPY config.template.json /

COPY docker-entry.sh /
RUN chmod +x /docker-entry.sh
ENTRYPOINT ["/docker-entry.sh"]

EXPOSE 80

```

nginx config (mattermost-ssl) in **_web_** container

```
# server {
#     listen         80;
#     server_name    mattermost.example.com;
#     return         301 https://$server_name$request_uri;
# }

server {
    listen 443 ssl;
    server_name [redacted];
    ssl on;
    ssl_certificate /cert/oss-mattermost.cer;
    ssl_certificate_key /cert/oss-mattermost.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:MEDIUM:!SSLv2:!PSK:!SRP:!ADH:!AECDH;
    ssl_prefer_server_ciphers on;

    location / {
        gzip off;
        proxy_set_header X-Forwarded-Ssl on;

        client_max_body_size 50M;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Frame-Options SAMEORIGIN;
        proxy_pass http://app:APP_PORT;
    }
}

```
